
const MODELS=[
 ['GPT-6 Astra','openai/gpt-6-astra'],['GPT-6 Astra Pro','openai/gpt-6-astra-pro'],
 ['Claude Opus 5','anthropic/claude-opus-5'],['Claude Fable 5','anthropic/claude-fable-5'],
 ['Claude Fable 5.1','anthropic/claude-fable-5-1'],['GPT-OSS 120B','openai/gpt-oss-120b'],['GPT-OSS 20B','openai/gpt-oss-20b']
];
const MODES={
 General:'Act as a practical senior software engineer. Be correct, concise, and explicit about assumptions.',
 Build:'Act as a senior full-stack engineer. Produce maintainable production code, file structure, validation, error handling, tests, security, and deployment considerations.',
 Debug:'Act as a debugging specialist. Separate observed facts, likely causes, and fixes. Identify root cause before changing code. End with a verification step.',
 Review:'Act as a strict code reviewer. Find correctness bugs, edge cases, security issues, performance problems, maintainability risks, and missing tests. Prioritize by impact.',
 Architecture:'Act as a software architect. Analyze components, data flow, interfaces, failure modes, observability, scalability, security, cost, and tradeoffs.',
 Refactor:'Act as a refactoring specialist. Preserve behavior unless asked otherwise. Reduce duplication, coupling, complexity, and hidden state; include regression tests.',
 Testing:'Act as a senior test engineer. Design valuable unit, integration, end-to-end, property-based, and failure-path tests as appropriate.',
 SQL:'Act as a senior data engineer. Check joins, NULL semantics, duplicates, indexes, transactions, query plans, and SQL-dialect compatibility.',
 DevOps:'Act as an SRE/DevOps engineer. Focus on reproducibility, containers, CI/CD, secrets, least privilege, observability, rollback, reliability, and cost.',
 Security:'Act as an application-security engineer. Threat-model the design, identify concrete attack paths, protect secrets, enforce authorization, and distinguish exploitable issues from theoretical concerns.',
 DataML:'Act as a senior data scientist/ML engineer. Check leakage, validation, reproducibility, baselines, metrics, feature engineering, serving, and monitoring.',
 Git:'Act as a Git/GitHub expert. Prefer safe reversible workflows. Help with branches, commits, rebase/merge, conflicts, PRs, and releases without inventing repository state.',
 Docs:'Act as a technical writer for developers. Produce precise READMEs, API docs, architecture notes, changelogs, and examples.'
};
let S={chats:[],active:null,model:'anthropic/claude-fable-5-1',mode:'General',temp:.2,maxTokens:8192,reasoning:'medium',extra:'',files:[],generating:false};
const $=id=>document.getElementById(id), uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(), iso=()=>new Date().toISOString();
function toast(x){const t=$('toast');t.textContent=x;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function save(){localStorage.setItem('puter-dev-chat',JSON.stringify({chats:S.chats,active:S.active,model:S.model,mode:S.mode,temp:S.temp,maxTokens:S.maxTokens,reasoning:S.reasoning,extra:S.extra}))}
function load(){try{const x=JSON.parse(localStorage.getItem('puter-dev-chat')||'null');if(x)Object.assign(S,x)}catch{}if(!Array.isArray(S.chats))S.chats=[];ensure()}
function ensure(){if(!S.chats.find(c=>c.id===S.active)){const c={id:uid(),title:'New chat',model:S.model,mode:S.mode,createdAt:iso(),updatedAt:iso(),messages:[]};S.chats.unshift(c);S.active=c.id}}
function chat(){return S.chats.find(c=>c.id===S.active)}
function modelName(id){return MODELS.find(x=>x[1]===id)?.[0]||id}
function renderModels(live=[]){const m=new Map((live||[]).map(x=>[x.id,x]));$('model').innerHTML=MODELS.map(x=>`<option value="${x[1]}">${m.has(x[1])?'✓ ':'• '}${x[0]}</option>`).join('');$('model').value=chat()?.model||S.model;S.model=$('model').value}
async function refreshModels(){try{const live=await puter.ai.listModels();renderModels(live);$('status').textContent=`${live.length} models detected`; }catch{$('status').textContent='Model catalog unavailable';renderModels([])}}
async function authState(){try{if(puter.auth.isSignedIn()){const u=await puter.auth.getUser();const n=u?.username||u?.email||'Puter user';$('username').textContent=n;$('authState').textContent='Signed in';$('avatar').textContent=n[0].toUpperCase();$('authBtn').textContent='Switch'}else{$('username').textContent='Not signed in';$('authState').textContent='Click Sign in to authenticate';$('avatar').textContent='?';$('authBtn').textContent='Sign in'}}catch{}}
async function signin(){try{await puter.auth.signIn({request_auth:true});await authState();toast('Signed in')}catch{toast('Sign-in cancelled or failed')}}
function renderList(){const q=$('search').value.toLowerCase();$('chatList').innerHTML='';for(const c of S.chats.filter(c=>!q||c.title.toLowerCase().includes(q)||c.messages.some(m=>String(m.content||'').toLowerCase().includes(q)))){const r=document.createElement('div');r.className='chat'+(c.id===S.active?' active':'');r.innerHTML='<span class="dot"></span><span class="title"></span><button class="del">⋯</button>';r.querySelector('.title').textContent=c.title;r.onclick=e=>{if(e.target.classList.contains('del')){e.stopPropagation();if(confirm('Delete this chat?')){S.chats=S.chats.filter(x=>x.id!==c.id);ensure();save();renderAll()}}else{S.active=c.id;renderAll();save()}};$('chatList').appendChild(r)}}
function renderMsgs(){const host=$('messages'),c=chat();host.innerHTML='';if(!c||!c.messages.length){host.innerHTML='<div class="empty"><h2>What are you building?</h2><p>Frontier and open models through Puter.js, with focused developer modes.</p><div class="chips"><button class="chip">Review this Python function for bugs</button><button class="chip">Design a production FastAPI service</button><button class="chip">Debug this React state issue</button><button class="chip">Write tests for this code</button></div></div>';host.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{$('prompt').value=b.textContent;grow();$('prompt').focus()});return}for(let i=0;i<c.messages.length;i++){const m=c.messages[i];if(m.role==='system')continue;const a=document.createElement('article');a.className='message '+m.role+(m.error?' error':'');const body=document.createElement('div');body.className='body';if(m.role==='assistant'&&!m.error){body.innerHTML=DOMPurify.sanitize(marked.parse(String(m.content||''),{gfm:true,breaks:true}))}else body.textContent=String(m.content||'');const bubble=document.createElement('div');const meta=document.createElement('div');meta.className='meta';meta.textContent=m.role==='user'?'You':(m.modelName||'Assistant');bubble.append(meta,body);const icon=document.createElement('div');icon.className='icon';icon.textContent=m.role==='user'?'You':'AI';const actions=document.createElement('div');actions.className='actions';if(m.role==='assistant'&&!m.error){const b=document.createElement('button');b.textContent='Copy';b.onclick=()=>navigator.clipboard.writeText(m.content).then(()=>toast('Copied'));actions.append(b);if(i===c.messages.length-1){const r=document.createElement('button');r.textContent='Regenerate';r.onclick=()=>regen();actions.append(r)}}if(m.role==='user'){const e=document.createElement('button');e.textContent='Edit & resend';e.onclick=()=>editMsg(i);actions.append(e)}if(actions.childElementCount)bubble.append(actions);a.append(icon,bubble);host.append(a)}decorate(host);host.scrollTop=host.scrollHeight}
function decorate(root){root.querySelectorAll('pre code').forEach(code=>{try{hljs.highlightElement(code)}catch{};const pre=code.parentElement;if(pre.parentElement.classList.contains('code'))return;const wrap=document.createElement('div');wrap.className='code';pre.replaceWith(wrap);wrap.append(pre);const b=document.createElement('button');b.className='copycode';b.textContent='Copy';b.onclick=()=>navigator.clipboard.writeText(code.textContent).then(()=>{b.textContent='Copied';setTimeout(()=>b.textContent='Copy',900)});wrap.append(b)})}
function renderTop(){const c=chat();$('chatTitle').textContent=c?.title||'New chat';$('model').value=c?.model||S.model}
function renderAll(){renderList();renderMsgs();renderTop();renderSettings()}
function promptSystem(){return `You are a senior software-development AI assistant inside Puter Dev Chat.\n${MODES[S.mode]}\n\nRules:\n- Prefer runnable, idiomatic solutions over vague advice.\n- Never invent APIs, flags, files, repository state, benchmark results, or execution results.\n- For debugging, distinguish evidence, hypothesis, fix, and verification.\n- For code, include validation, error handling, security, and tests when relevant.\n- Protect credentials and private data.\n- Ask only when an essential requirement is missing; otherwise state assumptions and proceed.`+(S.extra.trim()?`\n\nAdditional instructions:\n${S.extra}`:'')}
function textResp(x){if(!x)return'';if(typeof x==='string')return x;const c=x.message?.content??x.content??x.text;if(typeof c==='string')return c;if(Array.isArray(c))return c.filter(v=>v?.type==='text').map(v=>v.text||'').join('');return ''}
function streamText(x){if(!x)return'';if(x.type==='error')throw new Error(x.message||'Puter streaming error');if(x.type==='text'&&typeof x.text==='string')return x.text;return''}
function grow(){const t=$('prompt');t.style.height='auto';t.style.height=Math.min(t.scrollHeight,220)+'px'}
async function send(){if(S.generating)return;const p=$('prompt').value.trim();if(!p&&!S.files.length)return;const c=chat();if(!c.messages.length)c.title=(p||'Attached files').slice(0,80);c.model=S.model;c.mode=S.mode;let content=p;if(S.files.length)content+='\n\n'+S.files.map(f=>`--- FILE: ${f.name} ---\n\`\`\`${f.lang}\n${f.text}\n\`\`\``).join('\n\n');c.messages.push({role:'user',content,createdAt:iso()});S.files=[];$('prompt').value='';renderFiles();grow();c.updatedAt=iso();save();renderAll();await generate(c)}
async function generate(c){S.generating=true;$('sendBtn').style.display='none';$('stopBtn').style.display='';const a={role:'assistant',content:'',model:c.model,modelName:modelName(c.model),createdAt:iso()};c.messages.push(a);let stopped=false;S.cancel=()=>{stopped=true;S.generating=false;toast('Stop requested')};try{const opts={model:c.model,stream:true,max_tokens:Number(S.maxTokens),temperature:Number(S.temp)};if(S.reasoning)opts.reasoning_effort=S.reasoning;const messages=[{role:'system',content:promptSystem()},...c.messages.slice(0,-1).map(m=>({role:m.role,content:m.content}))];const r=await puter.ai.chat([...messages],opts);if(r&&typeof r[Symbol.asyncIterator]==='function'){for await(const part of r){if(stopped)break;const t=streamText(part);if(t){a.content+=t;renderMsgs()}}}else{a.content=textResp(r);renderMsgs()}if(!a.content&&!stopped)a.content='[No text returned]';c.updatedAt=iso();save()}catch(e){a.error=true;a.content=(e&&e.message)||String(e);renderMsgs()}finally{S.generating=false;S.cancel=null;$('sendBtn').style.display='';$('stopBtn').style.display='none';$('status').textContent='';save();renderList()}}
function regen(){const c=chat();if(!c||S.generating)return;if(c.messages.length<2)return;c.messages.pop();save();renderMsgs();generate(c)}
function editMsg(i){const c=chat(),m=c.messages[i];if(!m||m.role!=='user')return;$('prompt').value=m.content;c.messages=c.messages.slice(0,i);save();renderAll();grow();$('prompt').focus()}
function lang(n){const e=(n.split('.').pop()||'').toLowerCase();return({js:'javascript',jsx:'javascript',ts:'typescript',tsx:'typescript',py:'python',java:'java',c:'c',cpp:'cpp',cs:'csharp',go:'go',rs:'rust',php:'php',rb:'ruby',sql:'sql',html:'html',css:'css',json:'json',yaml:'yaml',yml:'yaml',sh:'bash',ps1:'powershell',md:'markdown',xml:'xml'})[e]||''}
async function files(fs){S.files=[];for(const f of fs){try{S.files.push({name:f.name,text:await f.text(),lang:lang(f.name)})}catch{toast('Could not read '+f.name)}}renderFiles()}
function renderFiles(){$('files').innerHTML=S.files.map((f,i)=>`<span class="filepill">${f.name}<button onclick="S.files.splice(${i},1);renderFiles()">×</button></span>`).join('')}
function renderSettings(){$('systemPrompt').value=S.extra;$('temperature').value=S.temp;$('tempValue').textContent=S.temp;$('maxTokens').value=S.maxTokens;$('reasoning').value=S.reasoning;$('modes').innerHTML=Object.keys(MODES).map(m=>`<button class="mode ${m===S.mode?'active':''}" data-mode="${m}">${m}</button>`).join('');$('modes').querySelectorAll('button').forEach(b=>b.onclick=()=>{S.mode=b.dataset.mode;renderSettings();renderTop();save()})}
async function usage(){try{if(!puter.auth.isSignedIn())await signin();const u=await puter.auth.getMonthlyUsage();alert(JSON.stringify(u,null,2))}catch(e){alert(String(e?.message||e))}}
async function cloudSave(){try{if(!puter.auth.isSignedIn())await signin();const c=chat();await puter.kv.set('devchat:'+c.id,c);const idx=await puter.kv.get('devchat:index')||[];if(!idx.some(x=>x.id===c.id))idx.push({id:c.id,title:c.title,updatedAt:c.updatedAt});await puter.kv.set('devchat:index',idx);toast('Saved to Puter KV')}catch(e){toast('Cloud save failed')}}
async function cloudLoad(){try{if(!puter.auth.isSignedIn())await signin();const idx=await puter.kv.get('devchat:index')||[];for(const x of idx.slice(-50)){const c=await puter.kv.get('devchat:'+x.id);if(c)S.chats=[...S.chats.filter(y=>y.id!==c.id),c]}S.chats.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));ensure();save();renderAll();toast('Loaded '+idx.length+' saved chats')}catch{toast('Cloud load failed')}}
$('newBtn').onclick=()=>{const c={id:uid(),title:'New chat',model:S.model,mode:S.mode,createdAt:iso(),updatedAt:iso(),messages:[]};S.chats.unshift(c);S.active=c.id;save();renderAll()};$('authBtn').onclick=signin;$('settingsBtn').onclick=()=>$('drawer').classList.add('open');$('closeBtn').onclick=()=>$('drawer').classList.remove('open');$('drawer').onclick=e=>{if(e.target===$('drawer'))$('drawer').classList.remove('open')};$('model').onchange=e=>{S.model=e.target.value;const c=chat();c.model=S.model;save();renderTop()};$('sendBtn').onclick=send;$('stopBtn').onclick=()=>S.cancel?.();$('prompt').addEventListener('input',grow);$('prompt').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();send()}});$('attachBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>files([...e.target.files]);$('search').oninput=renderList;$('clearBtn').onclick=()=>{if(confirm('Clear this chat?')){chat().messages=[];save();renderAll()}};$('exportBtn').onclick=()=>{const b=new Blob([JSON.stringify(chat(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=(chat().title||'chat').replace(/[^\w-]+/g,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const c=JSON.parse(await f.text());c.id=c.id||uid();S.chats=[c,...S.chats.filter(x=>x.id!==c.id)];S.active=c.id;save();renderAll();toast('Imported')}catch{toast('Invalid chat JSON')}};$('temperature').oninput=e=>{S.temp=+e.target.value;$('tempValue').textContent=S.temp;save()};$('maxTokens').oninput=e=>{S.maxTokens=+e.target.value;save()};$('reasoning').onchange=e=>{S.reasoning=e.target.value;save()};$('systemPrompt').oninput=e=>{S.extra=e.target.value;save()};$('usageBtn').onclick=usage;$('cloudSave').onclick=cloudSave;$('cloudLoad').onclick=cloudLoad;
load();renderAll();authState();refreshModels();
